### ISSUE TITLE
Typo in MD

### ISSUE THREAD

**Issue by MegaAndroidDeveloper666** [yandex/scout#6]
Hi there!

There is a typo in docs/essential rules.md.
At the "[Request should be synchronous](https://github.com/yandex/scout/blob/main/docs/essential-rules.md#request-should-be-synchronous)" section you have a typo:
 `Сomponent сдфыы provides special methods for obtaining Lazy and Provider.`

**Comment by bejibx** [comment]
Thanks for reporting this! Fixed here https://github.com/yandex/scout/pull/7
